_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "2":
                - 1
                - 5
                - 35
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.18.1
            "8":
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
batch_size:
    value: 16
learning_rate:
    value: 0.0001939044801896184
lr_scheduler:
    value: ReduceLROnPlateau
model_name:
    value: resnet
optimizer:
    value: Adam
weight_decay:
    value: 0.0001
