training:
  batch_size: 16
  validation_ratio: 0.2
  num_epochs: 50
  additional_train: True
  additional_epochs: 5
  learning_rate: 0.0001
  n_splits: 3

  metric: "accuracy"
  criterion: "CrossEntropyLoss"

  optimizer: "Adam"
  weight_decay: 0.0001

  lr_scheduler:
    name: "ReduceLROnPlateau"
    factor: 0.1
    patience: 3
    min_lr: 1e-6
    monitor: 'metric'

  early_stopping:
    patience: 5
    min_delta: 0.001
    evidence: 'loss'
    monitor: 'metric'

  pseudo_labeling : False
  confidence_threshold: 0.8
  interval : 5
model:
  name: "eff4"
  pretrained: True
  num_classes: 1000
